using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Interactivity;
using AzureTtsBatchStudio.ViewModels;

namespace AzureTtsBatchStudio.Views
{
    public partial class StoryBuilderView : UserControl
    {
        public StoryBuilderView()
        {
            InitializeComponent();
            DataContext = new StoryBuilderViewModel();
        }

        private void ShowQuickStart_Click(object? sender, RoutedEventArgs e)
        {
            // Find and show the help panel
            if (this.FindControl<Border>("HelpPanel") is Border helpPanel)
            {
                helpPanel.IsVisible = true;
            }
        }

        private void HideQuickStart_Click(object? sender, RoutedEventArgs e)
        {
            // Find and hide the help panel
            if (this.FindControl<Border>("HelpPanel") is Border helpPanel)
            {
                helpPanel.IsVisible = false;
            }
        }

        private void OpenSettings_Click(object? sender, RoutedEventArgs e)
        {
            // Navigate up to find the MainWindow and execute OpenSettingsCommand
            if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {
                if (desktop.MainWindow?.DataContext is MainWindowViewModel mainViewModel)
                {
                    // Use the command property generated by RelayCommand
                    if (mainViewModel.OpenSettingsCommand.CanExecute(null))
                    {
                        mainViewModel.OpenSettingsCommand.Execute(null);
                    }
                }
            }
        }
    }
}